### ISSUE TITLE
THIS IS NOT THE ISSUE... THIS IS A HUMBLE SUGGESTION FROM ME TO YOU...

### ISSUE THREAD

**Issue by DurgeshKavate003** [couldbejake/StoryChat#1]
Please Deploy this website... It can be done in less than 10 clicks in the github itself...

Go to the The `Setttings` of the Repository.

Then Click on the `Pages` Tab.

Then select the branch. In your case `main` branch.

And then click the `Save Button`. And the after 1 - 2 Minutes refresh the page you will get the link..

PLEASE DO THIS.

**Comment by couldbejake** [comment]
Hi @DurgeshKavate003, this application is actually available at https://couldbejake.io/StoryChat/ !

**Comment by DurgeshKavate003** [comment]
Yay... THANKS
